before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/pvn-wrapper
    goos:
      - linux
      - windows
      - darwin
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

release:
  github:
    owner: prodvana
    name: pvn-wrapper
  mode: replace
