name: build-docker-image

on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PUBLIC_REGISTRY: us-docker.pkg.dev/pvn-infra/pvn-public

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/868387978158/locations/global/workloadIdentityPools/pvn-infra/providers/github"
          service_account: "public-docker-write@pvn-infra.iam.gserviceaccount.com"
          token_format: "access_token"
          create_credentials_file: true
      - uses: "docker/login-action@v1"
        with:
          registry: "us-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.PUBLIC_REGISTRY }}/pvn-wrapper:latest
            ${{ env.PUBLIC_REGISTRY }}/pvn-wrapper:${{ github.sha }}
